Ext.define('PDA.Global', {
    alias: 'widget.Global',
    singleton: true,

    DEFAULT_PAGE_SIZE:  10,

    EVENT_PREDICTED_NEAR_FAILURE: 'near_failure',
    EVENT_HOST: 'host',
    EVENT_HYPERVISOR: 'hypervisor',
    EVENT_VM: 'vm_name',

    ACTION_EMAIL_PREFIX: 'action.email.',
    ACTION_ARCSERVE_PREFIX: 'action.cmd.arcserve.',
    ACTION_CMD_RAW_PREFIX:  'action.cmd.raw.',
    ACTION_PS_CMD_PREFIX:   'action.ps.raw.',
    ACTION_NOOP_PREFIX:     'action.noop',
    ACTION_LOG_PREFIX:      'action.log.',
    ACTION_SMS_TWILIO_PREFIX:      'action.sms.twilio.',
    ACTION_DRP_UPDATE_PREFIX:  'action.drprophet.schedule.update.',
    ACTION_DRP_RESTORE_PREFIX:  'action.drprophet.schedule.restore.',
    ACTION_DRP_SNAPSHOT_PREFIX:   'action.drprophet.snapshot.',

    ACTION_EMAIL: 'Email Alert',
    ACTION_ARCSERVE: 'ArcServe Command',
    ACTION_CMD_RAW:  'Windows Command',
    ACTION_PS_CMD:   'PowerShell Command',
    ACTION_NOOP:     'No Op',
    ACTION_LOG:      'Log',
    ACTION_SMS_TWILIO:      'SMS Twilio',
    ACTION_DRP_UPDATE: 'DRProphet Update Schedule',
    ACTION_DRP_RESTORE: 'DRProphet Restore Schedule',
    ACTION_DRP_SNAPSHOT: 'DRProphet Create Snapshot',

    PDA_TITLE: 'Predictive Data Adapter',
    APPLICATION_DRPROPHET: 'DRProphet',
    APPLICATION_ARCSERVE: 'Arcserve',
    
    HOST_ALL:           '-ALL-',
    HYPERVISOR_ALL:     '--------',
    VM_ALL:             '-VM ALL-',
    VM_DEFAULT:         '--------',

    PRODUCT_FULL:       'ProphetStor Federator',
    PRODUCT_SHORT:      'Federator',
    DEFAULT_USER:       'admin',
    EMAIL_REGISTER:     'register@prophetstor.com',
    PRIMARY_DISK:       'Primary Disk',
    VIRTUAL_DISK:       'Virtual Disk',
    REPLICA_DISK:       'Replica Disk',
    CLICK_DETAIL:       'Click for detail',
    FEDHOME:            '/opt/prophetstor/federator',
    DOWNLOAD_PATH:      '/var/tmp',
    NA: 'N/A',
    DASH: '-',
    DASHDASH: '--',
    

    COMBO_ALL:          '-- All --',
    LANGUAGES:[
        ['en', 'English', 'ascii'],
        ['zh_CN', '\u7B80\u4F53\u4E2D\u6587']
    ],
    THRUPUT_MAX_VAL: 1000000000000,
    CANCEL_NOTI_FLASH_MS: 3000,
    AUTO_FLOAT_LOG_DELAY_MS: 500,
    CANCEL_LOG_NOTI_MS: 3000,
    MAX_FIXED_FLOAT_LOG_HEIGHT: 300,
    FIXED_FLOAT_LOG_HEIGHT: 200,
    FLOAT_LOG_HEIGHT: 300,
    FLOAT_LOG_COUNT: 99,
    VPORT_CT_WIDTH: 715 * 1.618,
    VPORT_CT_HEIGHT: 880,
    FED_MENU_HIDED_SHIFT: 136,
    VPORT_CT_WIDTH_HIDED: 715 * 1.618 - 136,//Global.VPORT_CT_WIDTH - Global.FED_MENU_HIDED_SHIFT
    FED_MENU_WIDTH: 200,
    FED_MENU_WIDTH_HIDED: 200 - 136,//Global.FED_MENU_WIDTH - Global.FED_MENU_WIDTH_HIDED
    FED_HOME_HEIGHT: 750,

    DELAY_CLICK_TIME: 200,
    MENU_ADJUST_ON_DBLCLICK: false,

    /*customization setting*/
    FED_DEFAULT_TOTAL_SECTOR_OFFSET: 2048,
    FED_MAX_DESC_MAX:               256,
    FED_MAX_HOSTNAME_LEN:            256,
    FED_MAX_VOLNAME_LEN:             128,
    FED_MAX_POOLNAME_LEN:             128,
    FED_MAX_OFFERINGNAME_LEN:          128,
    FED_MAX_SNAPSHOTNAME_LEN:          128,
    FED_MAX_INITIATORNAME_LEN:          128,
    FED_MAX_REMARK_LEN:           256,
    FED_MAX_DISKTYPE_LEN:           256,
    FED_MAX_DISKMODEL_LEN:           256,
    FED_MAX_DISKVENDOR_LEN:           256,
    FED_MAX_DISKNAME_LEN:           128,
    FED_MAX_POOLNAME_LEN:           128,
    FED_MAX_USERNAME_LEN:           128,
    FED_MAX_IPV4_LEN:                16,
    FED_MAX_NETMASK_LEN:             16,
    FED_MAX_MAC_LEN:                 18,
    FED_MAX_IF_LEN:                  16,
    FED_MAX_VENDOR_NAME_LEN:         64,
    FED_MAX_MODEL_NAME_LEN:          64,
    FED_MAX_VERSION_LEN:             256,
    FED_MAX_STORAGE_NAME_LEN:        128,
    FED_MAX_STORAGE_ID_LEN:          64,
    FED_MAX_STORAGE_GUID_LEN:        64,
    FED_MAX_STORAGE_SERIAL_NO_LEN:   64,
    FED_MAX_FC_WWPN_LEN:             256,
    FLEX_HOSTNAME_LEN:               64,
    GENERIC_STORAGE_NAME_LEN:        128,
    ISCSI_IQN_LEN:                   255,
    FC_INITIATOR_MAX_LEN:            16,
    FC_INITIATOR_MAX_LEN_C:          23,
    IPv4_LEN:                        15,

    FLEX_POOL_MAX_PW:               3,

    HEALTH_STATUS_OK:               0,
    HEALTH_STATUS_WARNING:          1,
    HEALTH_STATUS_ERROR:            2,
    HEALTH_STATUS_CRITICAL:         3,

    FED_CONTAINER_HEIGHT:   180,

    ONE_G_BYTES:   1073741824,

    /* federator query couchDB table */
    //FED_QUERY_URL:          'http://172.31.7.105:5984/',
    FFF0:                   '\\ufff0',
    FED_QUERY_URL:          'http://127.0.0.1:5984/',
    FED_QUERY_STORAGE:      'ussfed_storage',
    FED_QUERY_POOL:         'ussfed_pool',
    FED_QUERY_OFFERING:     'ussfed_offering',
    FED_QUERY_VOLUME:       'ussfed_volume',
    FED_QUERY_USER:         'ussfed_user',
    FED_QUERY_IGROUP:       'ussfed_igroup',
    FED_QUERY_ORDER:        'ussfed_order',
    FED_QUERY_MONITORING:   'ussfed_monitoring',
    FED_QUERY_EVENT:        'ussfed_event',
    FED_QUERY_SYSTEM:       'ussfed_system',
    FED_QUERY_LICENSE:      'ussfed_license',
    FED_QUERY_TMM:          'ussfed_tmm',
    FED_QUERY_STOREVENT:    'ussfed_storevent',
    FED_QUERY_WORKLOAD:     'ussfed_workload',
    FED_QUERY_ADAPTER:      'ussfed_adapter',
    FED_QUERY_VOLGROUP:     'ussfed_volgroup',
    FED_QUERY_HA:           'ussfed_ha',
    FED_QUERY_JOB:          'ussfed_job',
    FED_QUERY_JOBHISTORY:   'ussfed_jobhistory',
    FED_QUERY_REPLICATION_SESSION_HISTORY:   'ussfed_replication_session_history',

    FED_QUERY_FAILOVER_URL: 'http://127.0.0.1:5985/',
    
    /*FED_QUERY_ALL_DOC:      '_all_docs?include_docs=true&endkey=\"_\"',*/
    FED_QUERY_ALL_DOC:      '_all_docs?include_docs=true',
    FED_QUERY_DESIGN_DOC:   '_design',
    FED_QUERY_VIEW:         '_view',
    FED_QUERY_LIST:         '_list',
    FED_QUERY_OPT_BY_NAME:  'by_name',
    
    /* federator execute curl command */
    //FED_PUT_URL:	    'https://172.31.7.105:8356/v1/',
    FED_DEFAULT_PORT: 8345,
    FED_PUT_URL:        'http://127.0.0.1:8345/',
    FED_PUT_STORAGE:	'fed_storage',
    FED_PUT_POOL:	    'fed_pool',
    FED_PUT_OFFERING: 	'fed_offering',
    FED_PUT_VOLUME:     'fed_volume',
    FED_PUT_USER:       'fed_user',
    FED_PUT_IGROUP:     'fed_igroup',
    FED_PUT_ORDER:      'fed_order',
    FED_PUT_SYSTEM:     'fed_system',
    FED_PUT_LICENSE:    'fed_license',
    FED_PUT_WORKLOAD:   'fed_workload',
    FED_PUT_TMM:        'fed_tmm',
    FED_PUT_VOLGROUP:   'fed_volgroup',
    FED_PUT_HA:         'fed_ha',
    FED_PUT_JOB:        'fed_job',
    FED_PUT_ZABBIX:     'fed_zabbix',
    FED_PUT_AGENT:      'fed_agent',
    FED_PUT_AUTH:       'fed_auth',
    FED_PUT_DISKPROPHET:    'diskprophet',

    AGENT_V1: 'v1',

    FED_VERSION_INFO:   'USS-Federation',

    /* federator items */
    FED_HOMES:          'Home',
    FED_STORAGE:        'Storage',
    FED_POOLS:          'Pools',
    FED_VOLUMES:        'Volumes',
    FED_OFFERINGS:      'Offerings',
    FED_SCHEDULERS:     'Schedulers',
    FED_MONITOR:        'Monitor',
    FED_SETTINGS:       'Settings',
    
    /* User items */
    FED_USER_SERVICES:      'Services',
    FED_USER_VOLUMES:       'Volumes',
    FED_USER_FILES:         'Files',
    FED_USER_BACKUPS:       'Backups',
    FED_USER_OBJECTS:       'Objects',
    FED_USER_ACCOUNT:       'Account', 

    /* pool type */
    FED_STORAGE_TYPE_BLOCK:     'Block',
    FED_STORAGE_TYPE_FILE:      'File',
    FED_STORAGE_TYPE_OBJECT:    'Object',

    /* pool protocol */
    FED_PROTOCOL_TYPE_ISCSI:    'iSCSI',
    FED_PROTOCOL_TYPE_FC:       'FC',
    FED_PROTOCOL_TYPE_RBD:      'RBD',

    /* pool policy */
    FED_POOL_POLICY_AUTO:       'Auto',
    FED_POOL_POLICY_STATIONARY: 'Static',
    FED_POOL_POLICY_MANUAL:     'Manual',
    FED_POOL_POLICY_POOL:       'Pool',
    FED_POOL_POLICY_DYNAMIC:    'Dynamic',

    /* federator database */
    FED_DB_POOL:        'ussfed_pool',
    FED_DB_VOLUME:      'ussfed_volume',
    FED_DB_OFFERING:    'ussfed_offering',
    FED_DB_SCHEDULER:   'ussfed_scheduler',
    FED_DB_USER:        'ussfed_user',
    FED_DB_EVENT:       'ussfed_event',
    FED_DB_STORAGE:     'ussfed_storage',
    FED_DB_WORKLOAD:    'ussfed_workload',
    FED_DB_ADAPTER:     'ussfed_adapter',
    FED_DB_VOLGROUP:    'ussfed_volgroup',

    FED_DB_STORAGE_VENDOR_PROPHETSTOR:      'ProphetStor',

    FED_DB_STORAGE_MODEL_FLEXVISOR:     'Flexvisor',
    FED_DB_STORAGE_APAPTER_FLEXVISOR:   'cdmi-dpl',

    CDMI_SNAPSHOTS:     'cdmi_snapshots',
    CDMI_REPLICATION:   'cdmi_replication',
    BACKUP_SETTING:     'backup_setting',
    EMAIL_ALERT:        'email_alert',
    XRAY_SUPPORT:       'support',

    /* general combo items */
    COMBO_TYPE:         '-- select type --',
    COMBO_FILTER_TYPE:  'Type',
    COMBO_FILTER_OWNER:  'Owner',
    COMBO_FILTER_PROTOCOL:  'Protocol',
    COMBO_FILTER_USED:      'Used',
    COMBO_FILTER_STATUS:    'Status',
    COMBO_FILTER_MODEL: 'Model',
    COMBO_FILTER_VENDOR: 'Vendor',
    COMBO_FILTER_STATUS: 'Status',
    COMBO_FILTER_NODE: 'Storage',
    COMBO_FILTER_STORAGE: 'Storage',
    COMBO_FILTER_POOL: 'Pool',
    COMBO_FILTER_OFFERING: 'Offering',
    COMBO_FILTER_SERVICE: 'Service',
    COMBO_FILTER_IOPS_AVAIL: 'IOPS Avail',
    COMBO_FILTER_AVAIL: 'Avail',
    COMBO_FILTER_POLICY: 'Policy',
    COMBO_FILTER_IOPS: 'IOPS',
    COMBO_FILTER_OS: 'OS',
    COMBO_FILTER_ASSIGN: 'Assign',
    COMBO_CONTENT:         '--select content--',
    COMBO_SEVERITY:         '--select severity--',
    COMBO_CRITICAL:'Critical',
    COMBO_ERROR:'Error',
    COMBO_WARNING:'Warning',
    COMBO_INFO:'Info',
    COMBO_CUSTOMIZED: '-- Customized --',
    COMBO_CUSTOMIZED_VALUE: -1,

    COMBO_FREQ_MONTH:       'month',
    COMBO_FREQ_WEEK:        'week',
    COMBO_FREQ_DAY:         'day',

    /* DPL default port*/
    DPL_DEFAULT_PORT:       8357,
    DPL_DEFAULT_PROTOCOL:   'https',

    /* protocol */
    PROTOCOL_HTTP:          'http',
    PROTOCOL_HTTPS:         'https',
    PROTOCOL_CEPH:          'ceph',
    PROTOCOL_IPSTOR:        'ipstor',
    PROTOCOL_NEXSAN:        'nmp',

    /* role */
    ROLE_AIO:               'aio',

    /* login role */
    LOGIN_ROLE_ADMIN:       'admin',
    LOGIN_ROLE_USER:        'user',
    LOGIN_ROLE_OPERATOR:    'operator',

    LOGIN_ROLE_ADMIN_N:     0x0001,
    LOGIN_ROLE_USER_N:      0x0010,
    LOGIN_ROLE_OPERATOR_N:  0x0100,

    /* importable pool status */
    IMPORTABLE_POOL:        ['online', 'degraded'],

    /* status string */
    STATUS_ONLINE:          'online',
    STATUS_OFFLINE:         'offline',
    STATUS_DEGRADED:        'degraded',
    STATUS_UNKNOWN:         'unknown',

    STATUS_COMPLETED: 'completed',
    STATUS_APPROVED: 'approved',
    STATUS_PENDING: 'pending',
    STATUS_PROCESSING: 'processing',
    STATUS_EXPIRED: 'expired',
    STATUS_DISABLED: 'disabled',
    STATUS_ACTIVE: 'active',
    STATUS_SKIPPED: 'skipped',
    STATUS_PARTIAL: 'partial',
    STATUS_FAILED: 'failed',
    STATUS_LOCKED:  'locked',

    STATUS_ONLINE_DISPLAY:          'Online',
    STATUS_OFFLINE_DISPLAY:         'Offline',
    STATUS_DEGRADED_DISPLAY:        'Degraded',
    STATUS_UNKNOWN_DISPLAY:         'Unknown',
    STATUS_REBUILDING_DISPLAY:      'Rebuilding',
    STATUS_READY_DISPLAY:           'ready',
    STATUS_FAULTY_DISPLAY:          'faulty',

    perfBtnText:            'Test',
    perfBtnOnTestText:      'Test Running',

    PERFORMANCE_TEST_STATUS_FAILED:         'Failed',
    PERFORMANCE_TEST_STATUS_PROCESSING:     'Processing',
    PERFORMANCE_TEST_STATUS_COMPLETE:       'Complete',

    PERFORMANCE_API_NAME:                   'FIO_USER',
    
    BYTES_PER_SEC: 'bytes/s',

    PERFORMANCE_TEST_BLOCKSIZE_512B:        '512 Bytes',
    PERFORMANCE_TEST_BLOCKSIZE_1K:          '1 KB',
    PERFORMANCE_TEST_BLOCKSIZE_2K:          '2 KB',
    PERFORMANCE_TEST_BLOCKSIZE_4K:          '4 KB',
    PERFORMANCE_TEST_BLOCKSIZE_8K:          '8 KB',
    PERFORMANCE_TEST_BLOCKSIZE_16K:         '16 KB',
    PERFORMANCE_TEST_BLOCKSIZE_32K:         '32 KB',
    PERFORMANCE_TEST_BLOCKSIZE_64K:         '64 KB',
    PERFORMANCE_TEST_BLOCKSIZE_128K:        '128 KB',

    EVENT_STATUS_COMPLETE:                  'Complete',
    EVENT_STATUS_PROCESSING:                'Processing',
    EVENT_STATUS_ERROR:                     'Error',

    VOLUME_EVENT_TYPE_VOL_CREATE: 'create-volume',
    VOLUME_EVENT_TYPE_SNAP_CLONE: 'clone-snapshot',
    VOLUME_EVENT_TYPE_VOL_CLONE: 'clone-volume',
    VOLUME_EVENT_TYPE_VOL_ROLLBACK: 'rollback-volume',
    VOLUME_EVENT_TYPE_IMAGE_TO_VOL: 'copy-image-to-volume',
    VOLUME_EVENT_TYPE_VOL_TO_IMAGE: 'copy-volume-to-image',
    VOLUME_EVENT_TYPE_VOL_ASSIGN: 'assign-volume',
    VOLUME_EVENT_TYPE_VOL_SPAWN: 'spawn-volume',
    VOLUME_EVENT_TYPE_VOL_DELETE: 'delete-volume',
    VOLUME_EVENT_TYPE_VOL_EXTEND: 'extend-volume',
    VOLUME_EVENT_TYPE_VOL_UPDATE: 'update-volume',
    VOLUME_EVENT_TYPE_VOL_CREATE_SNAPSHOT: 'create-volume-snapshot',
    VOLUME_EVENT_TYPE_VOL_DELETE_SNAPSHOT: 'delete-volume-snapshot',
    VOLUME_EVENT_TYPE_VOL_UPDATE_SNAPSHOT: 'update-volume-snapshot',
    VOLUME_EVENT_TYPE_VOL_DISCOVER: 'discover-volume',
    VOLUME_EVENT_TYPE_VOL_REPLAN: 'replan-volume',
    VOLUME_EVENT_TYPE_VOL_ENGAGE: 'engage-volume',
    VOLUME_EVENT_TYPE_VOL_DISENGAGE: 'disengage-volume',
    VOLUME_EVENT_TYPE_VOL_CREATE_REPLICATION: 'create-volume-replication',
    VOLUME_EVENT_TYPE_VOL_DELETE_REPLICATION: 'delete-volume-replication',
    VOLUME_EVENT_TYPE_VOL_UPDATE_REPLICATION: 'update-volume-replication',
    VOLUME_EVENT_TYPE_VOL_PROMOTE_VOLUME: 'promote-volume',
    VOLUME_EVENT_TYPE_VOL_INVENTORY_VOLUME: 'inventory-volume',
    VOLUMEGROUP_EVENT_TYPE_VG_CREATE: 'create-volume-group',
    VOLUMEGROUP_EVENT_TYPE_VG_DELETE: 'delete-volume-group',
    VOLUMEGROUP_EVENT_TYPE_VG_UPDATE: 'update-volume-group',
    VOLUMEGROUP_EVENT_TYPE_VG_JOIN: 'join-volume-group',
    VOLUMEGROUP_EVENT_TYPE_VG_LEAVE: 'leave-volume-group',
    VOLUMEGROUP_EVENT_TYPE_VG_SNAP_CLONE: 'clone-volume-group-snapshot',
    VOLUMEGROUP_EVENT_TYPE_VG_CLONE: 'clone-volume-group',
    VOLUMEGROUP_EVENT_TYPE_VG_ROLLBACK: 'rollback-volume-group',
    VOLUMEGROUP_EVENT_TYPE_VG_ASSIGN: 'assign-volume-group',
    VOLUMEGROUP_EVENT_TYPE_VG_SPAWN: 'spawn-volume-group',
    VOLUMEGROUP_EVENT_TYPE_VG_CREATE_SNAPSHOT: 'create-volume-group-snapshot',
    VOLUMEGROUP_EVENT_TYPE_VG_DELETE_SNAPSHOT: 'delete-volume-group-snapshot',
    VOLUMEGROUP_EVENT_TYPE_VG_UPDATE_SNAPSHOT: 'update-volume-group-snapshot',
    VOLUMEGROUP_EVENT_TYPE_VG_CREATE_REPLICATION: 'create-volume-group-replication',
    VOLUMEGROUP_EVENT_TYPE_VG_DELETE_REPLICATION: 'delete-volume-group-replication',
    VOLUMEGROUP_EVENT_TYPE_VG_UPDATE_REPLICATION: 'update-volume-group-replication',
    VOLUMEGROUP_EVENT_TYPE_VG_PROMOTE_VOLUMEGROUP: 'promote-volume-group',
    JOB_EVENT_TYPE_CREATE: 'create-job',
    JOB_EVENT_TYPE_UPDATE: 'update-job',
    JOB_EVENT_TYPE_DELETE: 'delete-job',
    BACKUP_EVENT_TYPE_BACKUP_CONFIG: 'backup-config',
    BACKUP_EVENT_TYPE_RESTORE_CONFIG: 'restore-config',
    BACKUP_EVENT_TYPE_DOWNLOAD_CONFIG: 'download-config',
    SYSTEM_MAINTENANCE_EVENT_TYPE_POWER_DOWN: 'power-down',
    POOL_EVENT_TYPE_PERF_PROFILING: 'performance-profiling',
    POOL_EVENT_TYPE_POOL_DISCOVER: 'discover-pool',
    POOL_EVENT_TYPE_POOL_INVENTORY: 'inventory-pool',
    POOL_EVENT_TYPE_POOL_REMOVAL: 'remove-pool',
    STORAGE_EVENT_TYPE_STORAGE_DISCOVER: 'discover-storage',
    STORAGE_EVENT_TYPE_STORAGE_INVENTORY: 'inventory-storage',
    STORAGE_EVENT_TYPE_STORAGE_DEREGISTER: 'deregister-storage',
    IGROUP_EVENT_TYPE_IG_UPDATE: 'update-igroup',
    HA_EVENT_TYPE_CREATE_CLUSTER: 'create-cluster',
    HA_EVENT_TYPE_PRECHECK_CLUSTER: 'precheck-cluster',
    HA_EVENT_TYPE_DELETE_CLUSTER: 'delete-cluster',
    HA_EVENT_TYPE_JOIN_CLUSTER: 'join-cluster',
    HA_EVENT_TYPE_LEAVE_CLUSTER: 'leave-cluster',
    HA_EVENT_TYPE_SUSPEND_CLUSTER: 'suspend-cluster',
    HA_EVENT_TYPE_RESUME_CLUSTER: 'resume-cluster',
    HA_EVENT_TYPE_PROMOTE_CLUSTER_NODE: 'promote-cluster-node',
    HA_ROLE_MASTER: 'Master',

    EVENT_STATUS_COMPLETE_LOWER:            'complete',
    EVENT_STATUS_PROCESSING_LOWER:          'processing',

    CREATE_OFFERING_POLICY_AUTO:    'Auto',
    CREATE_OFFERING_POLICY_MANUAL:  'Manual',
    CREATE_OFFERING_POLICY_DYNAMIC:    'Dynamic',
    CREATE_OFFERING_POLICY_POOL:    'Pool',

    CREATE_OFFERING_PUBLIC_PROPERTIES_REQUIRED: 'Required',
    CREATE_OFFERING_PUBLIC_PROPERTIES_PREFERRED: 'Preferred',
    CREATE_OFFERING_PUBLIC_PROPERTIES_DENIED: 'Denied',    

    PROVISION_TYPE_THIN:        'Thin',
    PROVISION_TYPE_THICK:       'Thick',
    PROVISION_TYPE_THICK_THIN:  'Thick/Thin',
    PROVISION_ALLOWED:          'Allowed',
    PROVISION_NOT_ALLOWED:      'Not allowed',

    SIZE_UNIT_MB:               'MB',
    SIZE_UNIT_GB:               'GB',
    SIZE_UNIT_TB:               'TB',
    SIZE_UNIT_PB:               'PB',
    SIZE_UNIT_ZB:               'ZB',

    THRUPUT_B:  'B/s',
    THRUPUT_KB: 'KB/s',
    THRUPUT_MB: 'MB/s',
    THRUPUT_GB: 'GB/s',

    BLOCK_SIZE_512B: '512 Bytes',
    BLOCK_SIZE_1K: '1 KB',
    BLOCK_SIZE_2K: '2 KB',
    BLOCK_SIZE_4K: '4 KB',
    BLOCK_SIZE_8K: '8 KB',
    BLOCK_SIZE_16K: '16 KB',
    BLOCK_SIZE_32K: '32 KB',
    BLOCK_SIZE_64K: '64 KB',
    BLOCK_SIZE_128K: '128 KB',

    BLOCK_SIZE_512B_VAL: 512,
    BLOCK_SIZE_1K_VAL: 1024,
    BLOCK_SIZE_2K_VAL: 2048,
    BLOCK_SIZE_4K_VAL: 4096,
    BLOCK_SIZE_8K_VAL: 8192,
    BLOCK_SIZE_16K_VAL: 16384,
    BLOCK_SIZE_32K_VAL: 32768,
    BLOCK_SIZE_64K_VAL: 65536,
    BLOCK_SIZE_128K_VAL: 131072,

    SNAPSHOT_FIRSTSELECTION:    '--Choose a snapshot--',
    COMBO_SELECT_NODE: '---select node---',

    ORDER_ACTION_STATE:         'Cancelled',

    ORDER_TYPE_CREATEVOLUME:    'Create-Volume',
    ORDER_TYPE_CLONEVOLUME:     'Clone-Volume',
    ORDER_TYPE_CLONESNAPSHOT:   'Clone-Snapshot',
    ORDER_TYPE_CREATEVOLFROMSNAPSHOT:   'Spawn-Volume',

    ORDER_TYPE_CREATEVOLUME_STR:    'Create Volume',
    ORDER_TYPE_CLONEVOLUME_STR:     'Clone Volume',
    ORDER_TYPE_CLONESNAPSHOT_STR:   'Clone Snapshot',
    ORDER_TYPE_CREATEVOLFROMSNAPSHOT_STR:   'Spawn Volume',

    MONITOR_TIMEFRAME_YEAR:     'year',
    MONITOR_TIMEFRAME_MONTH:    'month',
    MONITOR_TIMEFRAME_WEEK:     'week',
    MONITOR_TIMEFRAME_DAY:      'day',
    MONITOR_TIMEFRAME_HOUR:     'hour',
    MONITOR_TIMEFRAME_QUARTER:   'quarter',

    BACKUP_FREQ_MONTHLY:        'monthly',
    BACKUP_FREQ_WEEKLY:         'weekly',
    BACKUP_FREQ_DAILY:          'daily',
    BACKUP_FREQ_HOURLY:         'hourly',

    BACKUP_SCHEDULE_AM:         'AM',
    BACKUP_SCHEDULE_PM:         'PM',

    NUM_0:  '0',

    /* adapter type for federator discovery */
    ADAPTER_TYPE_IPSTOR:    'cli-ipstor',
    ADAPTER_TYPE_NEXENTA:   'nms-nexenta',
    ADAPTER_TYPE_DPL:       'cdmi-dpl',
    ADAPTER_TYPE_EMC:       'smis-emc',
    ADAPTER_TYPE_API_NETAPP:    'api-netapp',
    ADAPTER_TYPE_CEPH:      'api-ceph',
    ADAPTER_TYPE_NETAPP:    'smis-netapp',
    ADAPTER_TYPE_BIGTERA:  'api-bigtera',
    ADAPTER_TYPE_HP3PAR:    'api-3par',
    ADAPTER_TYPE_COMPELLENT:    'api-compellent',
    ADAPTER_TYPE_GENERIC:       'api-generic',
    ADAPTER_TYPE_NEXSAN:        'api-nexsan',
    ADAPTER_TYPE_CEPH_SC:   'api-sc',

    GENERIC_MODEL_HUAWEI_OCEANSTOR: 'Huawei OceanStor',
    GENERIC_MODEL_TYPE_DORADO:  'Dorado',
    GENERIC_MODEL_TYPE_HVS:     'HVS',
    GENERIC_MODEL_TYPE_T:       'T',

    VENDOR_HUAWEI:              'Huawei',

    GENERIC_DRV_DORADO_FC:      'cinder.volume.drivers.huawei.huawei_dorado.HuaweiDoradoFCDriver',
    GENERIC_DRV_DORADO_ISCSI:   'cinder.volume.drivers.huawei.huawei_dorado.HuaweiDoradoISCSIDriver',
    GENERIC_DRV_HVS_FC:         'cinder.volume.drivers.huawei.huawei_hvs.HuaweiHVSFCDriver',
    GENERIC_DRV_HVS_ISCSI:      'cinder.volume.drivers.huawei.huawei_hvs.HuaweiHVSISCSIDriver',
    GENERIC_DRV_T_FC:           'cinder.volume.drivers.huawei.huawei_t.HuaweiTFCDriver',
    GENERIC_DRV_T_ISCSI:        'cinder.volume.drivers.huawei.huawei_t.HuaweiTISCSIDriver',

    LICENSE_STATE_VALID:        'Valid',
    LICENSE_STATE_EXPIRED:      'Expired',
    LICENSE_STATE_TAKEOVER:     'Takeover',
    LICENSE_STATE_INVALID_DOMAIN:   'Invalid Domain',
    LICENSE_STATE_INVALID:      'Invalid',
    LICENSE_STATE_NO_LICENSE:   'No license',

    JOBHISTORY_STATE_COMPLETEID:    'Completed',
    JOBHISTORY_STATE_FAILED:        'Failed',
    JOBHISTORY_STATE_SKIPPED:       'Skipped',
    JOBHISTORY_STATE_PARTIAL:       'Partial',

    JOB_STATE_COMPLETEID:           'Completed',
    JOB_STATE_ERROR:                'Failed',
    JOB_STATE_ACITVE:               'Active',
    JOB_STATE_DISABLED:             'Disabled',

    LICENSE_TYPE_TRIAL:         'Trial License',
    LICENSE_TYPE_PURCHASED:     'Purchased License',

    LICENSE_CAP_UNLIMITED:      'Unlimited',

    /*Volume tye*/
    VOLUME_TYPE_VOLUME:         'Volume',
    VOLUME_TYPE_REPLICA:        'Replica',
    VOLUME_TYPE_SNAPSHOTVIEW:   'SnapshotView',
    VOLUME_TYPE_SNAPSHOT_VIEW:  'Snapshot View',
    /*Volume tye*/
    VG_TYPE_VOLUME:         'Volume',
    VG_TYPE_REPLICA:        'Replica',

    DELETE_BULK_SIZE:           20,
    VOL_DELETE_BULK_SIZE:       5,
    
    MONITOR_UPDATE_CYCLE1:60*1000,
    MONITOR_UPDATE_CYCLE2:30*60*1000,
    /*Monitoring category definition*/
    MONITORING_STORAGE: 1,
    MONITORING_POOL: 2,
    MONITORING_POOL_IMPORTED: 1,
    MONITORING_POOL_IMPORTABLE: 2,
    MONITORING_VOLUME: 3,
    MONITORING_FEDERATOR: 4,
    MONITORING_OFFERING: 999,
    MONITORING_PHYSICAL_DISK: 5,
    MONITORING_FC:  6,

    /*Monitoring status definition*/
    MONITORING_ONLINE: 1,
    MONITORING_OFFLINE: 2,
    MONITORING_DEGRADED: 3,
    MONITORING_UNKNOWN: 4,

    /*Monitoring cycle type*/
    MONITORING_IN_MINUTE: 1,
    MONITORING_HOURLY: 2,
    MONITORING_DAYLY: 3,
    MONITORING_MONTHLY: 4,
    
    TMM_CONFIDENCE_ORIGIN_PREDICT: 1,
    TMM_CONFIDENCE_UPPER_BOUND: 2,
    TMM_CONFIDENCE_LOWER_BOUND: 3,
    
    FED_API_USER_CREATE:            'create',
    FED_API_USER_UPDATE:            'update',

    FED_API_SYSTEMMAINTENANCE:      'system_maintenance',
    FED_API_POWERDOWN:              'power-down',
    FED_API_REBOOT:                 'reboot',
    FED_API_PACKAGE:                'package',
    FED_API_UPGRADE:                'upgrade',
    FED_API_ACTION:                 'action',
    FED_API_PACKAGE_TYPE_PATCH:     'patch',
    FED_API_PACKAGE_TYPE_UPGRADE:   'upgrade',
    FED_API_SITE:                   'site',

    FLEXVISOR_DB_PHYSICALDEVICE:    'dpl_physical_device',
    FLEXVISOR_DB_POOL:              'dpl_pool',
    FLEXVISOR_DB_SYSTEM:            'dpl_system',
    FLEXVISOR_DB_ACCOUNT:           'dpl_account',
    FLEXVISOR_DB_DISKCATEGORY:      'dpl_disk_category',
    FLEXVISOR_DB_VOLUME:            'dpl_volume',

    FLEX_API_ASYNC_TIMEOUT_COUNTER: 200,
    FLEXVISOR_API_VERSION:          'v1',
    FLEXVISOR_API_POOL:             'dpl_pool',
    FLEXVISOR_API_DPLDISK:          'dpl_disk',
    FLEXVISOR_API_VOLUME:           'dpl_volume',
    FLEXVISOR_API_VOLUMEGROUP:      'dpl_volgroup',
    FLEXVISOR_API_SNAPSHOT:         'cdmi_snapshots',
    FLEXVISOR_API_REPLICATION:      'cdmi_replication',
    FLEXVISOR_API_EXPORT:           'dpl_export',
    FLEXVISOR_API_STATISTICS:       'dpl_statistics',
    FLEXVISOR_API_LICENSE:          'dpl_license',
    FLEXVISOR_API_SYSTEM:           'dpl_system',
    FLEXVISOR_API_ACCOUNT:          'dpl_accountmgmt',
    FLEXVISOR_API_DISKCATEGORY:     'dpl_diskcategory',
    FLEXVISOR_API_CACHE:            'dpl_cache',
    FLEXVISOR_API_HA:               'dpl_ha',
    FLEXVISOR_API_ENCLOSURE:        'dpl_enclosure',
    FLEXVISOR_API_DISK:             'disk',
    FLEXVISOR_API_DEVICE:           'device',
    FLEXVISOR_API_XRAY_SUPPORT:     'support',
    FLEXVISOR_API_UTILITY:          'dpl_utility',
    FLEXVISOR_API_PREDICTION:       'dpl_prediction',
    FLEXVISOR_API_GETSCHEDULE:      'get_schedule',
    FLEXVISOR_API_SETBACKUPSCHEDULE:    'set_schedule',
    FLEXVISOR_API_SETBACKUPSERVER:  'set-backupserver',
    FLEXVISOR_API_SETBACKUPSCHEDULE_N:    'set-backupschedule',
    FLEXVISOR_API_LISTBACKUP:       'list_backup',
    FLEXVISOR_API_RESTORECONF:      'restore_conf',
    FLEXVISOR_API_TESTCONN:         'test_connect',
    FLEXVISOR_API_TESTCONN_OP:      'test-connectivity',
    FLEXVISOR_API_BACKUP_OP:        'backup',
    FLEXVISOR_API_RESTORE_OP:       'restore',
    FLEXVISOR_API_BACKUP:           'backup',
    FLEXVISOR_API_BACKUPCONF:       'backup_conf',
    FLEXVISOR_API_BACKUPSETTING:    'backup_setting',
    FLEXVISOR_API_MANAGEMENT:       'system_maintenance',
    FLEXVISOR_API_MAINTAIN:         'system_maintain',
    FLEXVISOR_API_SYSTEM_OP_UPDATE_HOSTNAME:    'op-update-hostname',
    FLEXVISOR_API_SYSTEM_OP_UPDATE_IP:          'op-update-network',
    FLEXVISOR_API_SYSTEM_OP_POWER_DOWN:         'power-down',
    FLEXVISOR_API_SYSTEM_OP_REBOOT:             'reboot-server',
    FLEXVISOR_API_SYSTEM_OP_POWER_ON:           'op-power-on-peer-node',
    FLEXVISOR_API_DEVICE_OP_ADD:                'add',
    FLEXVISOR_API_DEVICE_OP_UPDATE:             'update',
    FLEXVISOR_API_DEVICE_OP_REMOVE:             'remove',
    FLEXVISOR_API_DEVICE_OP_REPLACE:            'replace',
    FLEXVISOR_API_PHYSICALDEVICE:               'physical_device',
    FLEXVISOR_API_XRAY:             'xray',
    FLEXVISOR_API_CONFIGNETWORK_HA:         'confignetwork-ha',
    FLEXVISOR_INTERLINK_KEY:                'inter',
    FLEXVISOR_API_ENCLOSURE_SYSTEM:         'system',
    FLEXVISOR_API_SITE_OP:                  'site',

    FLEXVISOR_HA_STATUS_NORMAL:             'Normal',
    FLEXVISOR_HA_STATUS_RUNNING:            'Running',
    FLEXVISOR_HA_STATUS_SUSPEND:            'Suspend',

    FLEXVISOR_HA_NODE_STATUS_NORMAL:        'normal',
    FLEXVISOR_HA_NODE_STATUS_WANRING:       'warning',
    FLEXVISOR_HA_NODE_STATUS_FAILOVERING:   'failingover',
    FLEXVISOR_HA_NODE_STATUS_RECOVERING:    'recovering',
    FLEXVISOR_HA_NODE_STATUS_TAKING:        'taking',
    FLEXVISOR_HA_NODE_STATUS_RETURNING:     'returning',
    FLEXVISOR_HA_NODE_STATUS_UNKNOWN:       'unknown',
    FLEXVISOR_HA_NODE_STATUS_TAKEN:         'taken',
    FLEXVISOR_HA_NODE_STATUS_TAKE:          'take',
    FLEXVISOR_HA_NODE_STATUS_FAILED:        'failed',
    FLEXVISOR_HA_PRECHECK_OK:               'Good',
    FLEXVISOR_HA_PRECHECK_FAILED:           'Failed',
    FLEXVISOR_HA_HEALTH_ONLINE:             'Online',
    FLEXVISOR_HA_HEALTH_OFFLINE:            'Offline',

    FLEXVISOR_HA_RECOVER_AUTO:              'auto',
    FLEXVISOR_HA_RECOVER_MANUAL:            'manual',

    FLEXVISOR_HA_OP_PRECHECK:               'precheck-ha',
    FLEXVISOR_HA_OP_CONFIGHA:               'configure-ha',
    FLEXVISOR_HA_OP_SUSPEND:                'suspend',
    FLEXVISOR_HA_OP_RESUME:                 'resume',
    FLEXVISOR_HA_OP_FAILOVER:               'failover',
    FLEXVISOR_HA_OP_RECOVER:                'recover',
    FLEXVISOR_HA_OP_UPDATE:                 'update-ha',

    FLEXVISOR_ENCLOSURE_MODEL_GENERIC:      'Generic',
    //AIC
    FLEXVISOR_ENCLOSURE_MODEL_AIC_12G_HA201_Expander: 'AIC_12G_HA201_Expander',
    FLEXVISOR_ENCLOSURE_MODEL_AIC_HA201:    'AIC_HA201',
    FLEXVISOR_ENCLOSURE_JBOD_MODEL_AIC_2U24SAS3swap:    'AIC_2U24SAS3swap',
    //SMC
    FLEXVISOR_ENCLOSURE_MODEL_SMCI_SAS3x40: 'SMCI_SAS3x40',
    //FLEXVISOR_ENCLOSURE_MODEL_SMCI_SAS3x40_2U: 'LSI_SAS3x40_2U',
    FLEXVISOR_ENCLOSURE_JBOD_MODEL_LSI_SAS3x40_2U: 'LSI_SAS3x40_2U',
    FLEXVISOR_ENCLOSURE_MODEL_SMCDRS2U_SAS3x40: 'SMCDRS2U_SAS3x40',
    FLEXVISOR_ENCLOSURE_JBOD_MODEL_LSI_SAS3x40: 'LSI_SAS3x40',
    FLEXVISOR_ENCLOSURE_JBOD_MODEL_LSI_SAS3x40_24: 'LSI_SAS3x40_24',
    FLEXVISOR_ENCLOSURE_JBOD_MODEL_PROMISE_2U_SAS_24_SBB_BP: 'PROMISE_2U_SAS_24_SBB_BP',
    FLEXVISOR_ENCLOSURE_JBOD_MODEL_PROMISE_4U_SAS_24_12G_BP: 'PROMISE_4U_SAS_24_12G_BP',

    HD_MODEL_MICRON_S630DC_960:                  'MICRON_S630DC-960',
    HD_MODEL_TOSHIBA_AL14SEB120N:                'TOSHIBA_AL14SEB120N',

    ENCLOSURE_HD_EMPTY_COLOR:                   '#f5f5f5',

    FLEXVISOR_ENCLOSURE_SYSTEM_STATUS_NORMAL:   'normal',
    FLEXVISOR_ENCLOSURE_SYSTEM_STATUS_ERROR:    'error',
    FLEXVISOR_ENCLOSURE_SYSTEM_STATUS_WARNING:    'warning',
    FLEXVISOR_ENCLOSURE_SYSTEM_STATUS_NOTINSTALLED: 'not installed',
    FLEXVISOR_ENCLOSURE_IPMI_STATUS_UNSUPPORTED: 'unsupported',
    FLEXVISOR_ENCLOSURE_IPMI_STATUS_NONCRITICAL: 'nc',

    STATUS_OK:                        'OK',
    STATUS_ERROR:                     'Error',
    STATUS_WARNING:                   'Warning',
    STATUS_NOT_READY:                   'Not_Ready',
    
    FLEXVISOR_MGT_PROTOCOL_IPMI:            'IPMI',
    FLEXVISOR_MGT_PROTOCOL_IPMI_VALUE:            'ipmi',

    FLEXVISOR_HTTPCODE_NOTCONFIGHA:         404,
    FLEXVISOR_HTTPCODE_TIMEOUT:             408,

    FLEXVISOR_FC_HBA_MODE_INITIATOR:        'initiator',
    FLEXVISOR_FC_HBA_MODE_TARGET:           'target',

    FLEXVISOR_STORAGE_ADAPTER_TYPE_ISCSI:   'iscsi',
    FLEXVISOR_STORAGE_ADAPTER_TYPE_FC:      'fc',

    FLEXVISOR_ACCOUNT_TYPE_USER:            'user',
    FLEXVISOR_ACCOUNT_TYPE_GROUP:           'group',

    FLEXVISOR_CACHEMODE_AUTO:               'Auto',
    FLEXVISOR_CACHEMODE_MANUAL:             'Manual',

    FLEXVISOR_CACHEMODE_VAL_AUTO:           'auto',
    FLEXVISOR_CACHEMODE_VAL_MANUAL:         'manual',

    FLEXVISOR_DEFAULTUSER_ADMIN:           'admin',
    FLEXVISOR_DEFAULTUSER_GUEST:            'guest',

    FLEXVISOR_ZFS_CATE_DATA:                'data',
    FLEXVISOR_ZFS_CATE_SPARE:               'spare',
    FLEXVISOR_ZFS_CATE_CACHE:               'cache',
    FLEXVISOR_ZFS_CATE_EMPTY:               'empty',
    FLEXVISOR_ZFS_CATE_FOREIGN:             'foreign',
    FLEXVISOR_ZFS_CATE_PEER:                'peer',

    RAID_LEVEL_RAID0:                       'raid0',
    RAID_LEVEL_RAID10:                      'raid10',
    RAID_LEVEL_RAID5:                       'raid5',
    RAID_LEVEL_RAID6:                       'raid6',

    SECTOR_SIZE: 512,

    FILTER_OTHERS: -1,
    FILTER_OTHERS_STR:'Others',
    /*Storage Filter*/
    STORAGE_FILTER_MODEL:0,
    STORAGE_FILTER_VENDOR:1,
    STORAGE_FILTER_STATUS:2,
    STORAGE_SORT_MTIME:0,
    STORAGE_SORT_DISPLAYNAME:1,
    STORAGE_SORT_HAUUID: 2,

    /*Pool Filter*/
    POOL_FILTER_NODE: 0,
    POOL_FILTER_STORAGE: 0,
    POOL_FILTER_IOPS_AVAIL: 1,
    POOL_FILTER_TYPE: 2,
    POOL_FILTER_PROTOCOL: 3,
    POOL_FILTER_AVAIL: 4,
    POOL_FILTER_USED: 5,
    POOL_FILTER_STATUS: 6,
    POOL_SORT_MTIME: 0,
    POOL_SORT_DISPLAYNAME:1,
    POOL_SORT_SIZE:2,
    POOL_SORT_IOPS_TOTAL:3,
    /*Volume Filter*/
    VOLUME_FILTER_OWNER:0,
    VOLUME_FILTER_TYPE:1,
    VOLUME_FILTER_NODE:2,
    VOLUME_FILTER_STORAGE:2,
    VOLUME_FILTER_POOL:3,
    VOLUME_FILTER_OFFERING:4,
    VOLUME_FILTER_PROTOCOL:5,
    VOLUME_FILTER_STATUS:6,
    VOLUME_FILTER_ASSIGN:7,
    VOLUME_FILTER_VOLGROUP:8,
    VOLUME_SORT_TIME:0,
    VOLUME_SORT_DISPLAYNAME:1,
    VOLUME_SORT_VOLUME:1,
    VOLUME_SORT_SIZE:2,
    VOLUME_MNGVOL:0,
    VOLUME_UNMNGVOL:1,
    /*Volume Group Filter*/
    VOLUMEGROUP_FILTER_OWNER: 0,
    VOLUMEGROUP_FILTER_TYPE: 1,
    VOLUMEGROUP_FILTER_PROTOCOL: 2,
    VOLUMEGROUP_FILTER_STATUS: 3,
    VOLUMEGROUP_FILTER_ASSIGN: 4,
    VOLUMEGROUP_SORT_MTIME: 0,
    VOLUMEGROUP_SORT_DISPLAYNAME: 1,
    /*Offering Filter*/
    OFFERING_FILTER_TYPE:0,
    OFFERING_FILTER_PROTOCOL:1,
    OFFERING_FILTER_POLICY:2,
    OFFERING_FILTER_IOPS:3,
    OFFERING_SORT_MTIME:0,
    OFFERING_SORT_DISPLAYNAME:1,
    /*Replication Filter*/
    REPLICATION_FILTER_OWNER: 0,
    REPLICATION_FILTER_VOLNAME: 1,
    REPLICATION_FILTER_HOST: 2,
    REPLICATION_FILTER_ROLE: 3,
    REPLICATION_SORT_MTIME: 0,
    REPLICATION_SORT_DISPLAYNAME: 1,
    REPLICATION_SORT_VOL_DISPLAYNAME: 2,
    REPLICATION_SORT_HOST: 3,
    REPLICATION_SORT_ROLE: 4,
    REPLICATION_SESSION_RUNNING: 'Running',
    REPLICATION_SESSION_COMPLETED: 'Completed',
    REPLICATION_SESSION_FAILED: 'Failed',
    REPLICATION_SESSION_STOPPED: 'Stopped',
    REPLICATION_SESSION_SUSPENDED: 'Suspended',
    REPLICATION_ROLE_REPLICATOR: 'Replicator',
    REPLICATION_ROLE_REPLICA: 'Replica',
    /*VGReplication Filter*/
    VGREPLICATION_FILTER_OWNER: 0,
    VGREPLICATION_FILTER_VOLGROUP_NAME: 1,
    VGREPLICATION_FILTER_HOST: 2,
    VGREPLICATION_FILTER_ROLE: 3,
    VGREPLICATION_SORT_MTIME: 0,
    VGREPLICATION_SORT_DISPLAYNAME: 1,
    VGREPLICATION_SORT_VOL_DISPLAYNAME: 2,
    VGREPLICATION_SORT_HOST: 3,
    VGREPLICATION_SORT_ROLE: 4,
    VGREPLICATION_SESSION_RUNNING: 'Running',
    VGREPLICATION_SESSION_COMPLETED: 'Completed',
    VGREPLICATION_SESSION_FAILED: 'Failed',
    VGREPLICATION_SESSION_STOPPED: 'Stopped',
    VGREPLICATION_SESSION_SUSPENDED: 'Suspended',
    VGREPLICATION_ROLE_REPLICATOR: 'Replicator',
    VGREPLICATION_ROLE_REPLICA: 'Replica',

    /*Scheduler Filter*/
    SCHEDULER_FILTER_TYPE: 0,
    SCHEDULER_FILTER_OWNER: 1,
    SCHEDULER_SORT_MTIME: 0,
    SCHEDULER_SORT_DISPLAYNAME: 1,

    SCHEDULER_PATTERN_MONTH: 'Month',
    SCHEDULER_PATTERN_WEEK: 'Week',
    SCHEDULER_PATTERN_DAYOFWEEK: 'DayOfWeek',
    SCHEDULER_PATTERN_DAY_OF_WEEK: 'Day of week',
    SCHEDULER_PATTERN_DAY: 'Day(s)',
    SCHEDULER_PATTERN_HOUR: 'Hour(s)',
    SCHEDULER_PATTERN_MINUTE: 'Minute(s)',

    SCHEDULER_PATTERN_ONCE: 'Once',
    SCHEDULER_PATTERN_INTERVAL: 'Interval',
    SCHEDULER_PATTERN_HOURLY:   'Hourly',
    SCHEDULER_PATTERN_DAILY:    'Daily',
    SCHEDULER_PATTERN_WEEKLY:   'Weekly',
    SCHEDULER_PATTERN_MONTHLY:   'Monthly',
    /*Scheduler History Filter*/
    SCHEDULER_HISTORY_FILTER_TYPE: 0,
    SCHEDULER_HISTORY_FILTER_OWNER: 1,
    SCHEDULER_HISTORY_VOLUME_NAME: 2,
    SCHEDULER_HISTORY_VOLGROUP_NAME: 3,
    SCHEDULER_HISTORY_SORT_MTIME: 0,
    SCHEDULER_HISTORY_SORT_STARTTIME: 1,


    /*Schedule Type*/
    SCHEDULER_SCHEDULE_TYPE_SNAPSHOT: 'Snapshot',
    SCHEDULER_SCHEDULE_TYPE_GROUP_SNAPSHOT: 'GroupSnapshot',
    SCHEDULER_SCHEDULE_TYPE_REPLICATION: 'Replication',
    SCHEDULER_SCHEDULE_TYPE_GROUP_REPLICATION: 'GroupReplication',
    SCHEDULER_SCHEDULE_TYPE_CUSTOM: 'Custom',

    /*Workload*/
    WORKLOAD_TYPE_TEMP:     'Predefined',
    WORKLOAD_TYPE_USER:     'Customized',

    WORKLOAD_PATTERN_DAILY:     'Daily',
    WORKLOAD_PATTERN_WEEKLY:    'Weekly',
    WORKLOAD_PATTERN_MONTHLY:   'Monthly',
    WORKLOAD_PATTERN_YEARLY:    'Yearly',
    
    OFFERING_AUTO: 'Auto',
    OFFERING_POLICY_MANUAL: 'Manual',
    OFFERING_DYNAMIC: 'Dynamic',
    /*Initiator group filter*/
    INITIATORGRP_FILTER_PROTOCOL: 0,
    INITIATORGRP_FILTER_OS: 1,
    INITIATORGRP_FILTER_OWNER: 2,
    INITIATORGRP_SORT_MTIME: 0,
    INITIATORGRP_SORT_DISPLAYNAME: 1,
    /**/
    SNAPSHOT_SORT_MTIME: 0,
    SNAPSHOT_SORT_DISPLAYNAME: 1,
    SNAPSHOT_SORT_VOL_DISPLAYNAME: 2,
    SNAPSHOT_SORT_SNAPSHOT_TIMESTAMP: 3,
    SNAPSHOT_TYPE_VOLUME : 'Volume',
    SNAPSHOT_TYPE_VOLGROUP: 'VolGroup',
    SNAPSHOT_FILTER_OWNER: 0,
    SNAPSHOT_FILTER_VOLNAME: 1,

    GROUPSNAPSHOT_SORT_MTIME: 0,
    GROUPSNAPSHOT_SORT_DISPLAYNAME: 1,
    GROUPSNAPSHOT_SORT_VOLGROUP_DISPLAYNAME: 2,
    GROUPSNAPSHOT_SORT_SNAPSHOT_TIMESTAMP: 3,
    GROUPSNAPSHOT_FILTER_OWNER: 0,
    GROUPSNAPSHOT_FILTER_VOLGROUP_NAME: 1,

    REPL_HISTORY_TYPE_VOLUME: 'Volume',
    REPL_HISTORY_TYPE_VOLGROUP: 'VolGroup',

    DEFAULT_EXPANDER_HEIGHT: 250,    

    OFFERING_SLIDER_DEFAULT_MAX: 10000,
    OFFERING_TEXT_DEFAULT_MAX: 10000000,

    VOLUME_REQUEST_SIZE_GB: 17179869184,
    VOLUME_REQUEST_SIZE_TB: 16777216,

    FLEXVISOR_VERSION_3: 3,

    CUSTOMIZED_WORKLOAD_DATA: [{x:0,y:500},{x:1,y:500},{x:2,y:500},{x:3,y:500},{x:4,y:500},{x:5,y:500},{x:6,y:500},{x:7,y:500},{x:8,y:500},{x:9,y:500},{x:10,y:500},{x:11,y:500},{x:12,y:500},{x:13,y:500},{x:14,y:500},{x:15,y:500},{x:16,y:500},{x:17,y:500},{x:18,y:500},{x:19,y:500},{x:20,y:500},{x:21,y:500},{x:22,y:500},{x:23,y:500}],

    MAX_IOPS: 10000000,
    WORKLOAD_SHIFT_BY_DIFF: 0,
    WORKLOAD_SHIFT_BY_RATIO: 1,
    WORKLOAD_SHIFT_BY_DIFF_STR: 'By IOPS',
    WORKLOAD_SHIFT_BY_RATIO_STR: 'By ratio',

    VALIDATEIP: /(^([1-9][0-9]{0,1}|1[013-9][0-9]|12[0-689]|2[01][0-9]|22[0-3])([.]([1-9]{0,1}[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])){2}[.]([1-9][0-9]{0,1}|1[0-9]{2}|2[0-4][0-9]|25[0-4])$)|(127.0.0.1)/,

    VOLGROUP_ACTION_LEAVE: 'leave',
    VOLGROUP_ACTION_JOIN: 'join',

    FLEXVISOR_PRODUCT_SHORT: 'Flexvisor',
    CEPH_PRODUCT_SHORT: 'Ceph',
    CEPH_PHP: 'ceph',
    COPYRIGHT_YEAR: '2018',

    GRID_RELOAD_INTERVAL: 30, /*secords*/
    TIMEOUT_600S: 600000, 
    GRID_RELOAD_DEFER_60S: 60000,
    GRID_RELOAD_DEFER_300S: 300000,
    GRID_RELOAD_DEFER_600000MS: 600000,
    GRID_RELOAD_DEFER_MS: 30000,
    SLIDE_OUT_FLOAT_LOG_MS: 6000,

    CREDENTIAL_CEPH: 'ceph',

    CEPH_MEMBER_MON: 'monitor',
    CEPH_MEMBER_OSD: 'osd',

    CEPH_PROVIDER_LVM2: 'lvm2',
    CEPH_PROVIDER_FLEXVISOR: 'flexvisor',
    CEPH_PROVIDER_RAWDISK: 'rawdisk',

    CEPH_PHYSICAL_DISK: 'disk',
    CEPH_PHYSICAL_PARTITION: 'part',
    CEPH_MINIMUM_PG_NUM: 128,

    POLLING_INTERVAL: 3000,
    POLLING_FIRETYPE_ACTION: 'action',
    POLLING_FIRETYPE_QUERY: 'query',

    AJAX_METHOD_GET:        'GET',
    AJAX_METHOD_PUT:        'PUT',
    AJAX_METHOD_DELETE:     'DELETE',

    CHAP_METHOD:            'CHAP',

    HTTPCODE_UNAUTHORIZED:  401,

    MAINTENANCE_MODE_CODE:  '9098',

    HA_BKGC_SET:            ['efe9ec', 'ede4ef', 'ede5f7', 'd9ddf7', 'd4f7fd', 'd1e6e1', 'e5f5e2'],
    HA_BKGC_SET_1:          ['fffcf0', 'efefef', 'e5f5e2', 'd9ddf7', 'd4f7fd'],

    FLEX_CACHE_READ:        'read',
    FLEX_CACHE_WRITE:       'write',
    FLEX_CACHE_READWRITE:   'read/write',

    EXT_TYPEOF_BOOLEAN:     'boolean',
    EXT_TYPEOF_STRING:  'string',
    SCROLL_POS: {top:0, left: 0},
    OEMS: {
        SK: 'SK',
        PROPHETSTOR: 'ProphetStor',
        PROMISE: 'Promise',
        STELLARFLASH: 'StellarFlash',
        CETCSS: 'CETCSS'
    },
    DISABLE_HA: true,
    ENABLE_DISCOVER_STORAGE: false,
    ENABLE_IMPORTABELPOOL_APPLIANCE: false,
    RESTORE_CHECK_TIMES: 500,
    MARGIN_FOR_FOR_FLOAT_LOG: '0 0 7 0',

    SED_OP_UNLOCK:  'unlock_sed',
    SED_OP_RESET:   'reset_sed',
    SED_OP_GLOBAL_PASSWORD: 'sed_password',

    NIC_TYPE_ISCSI:     'iscsi_ip',
    NIC_TYPE_SERVICE:   'service_ip',
    NIC_TYPE_HEARTBEAT: 'heartbeat_ip',
    NIC_TYPE_MANAGEMENT:   'mgt_ip',
    NIC_TYPE_MAINTENANCE:   'maintenance_ip',

    NIC_TYPE_ISCSI_ISOLATION:           'iscsi',
    NIC_TYPE_HEARTBEAT_ISOLATION:       'heartbeat',
    NIC_TYPE_MANAGEMENT_ISOLATION:      'management',
    NIC_TYPE_MAINTENANCE_ISOLATION:     'maintenance',
    NIC_TYPE_ISCSIMANAGEMENT_ISOLATION: 'iscsi-management',
    NIC_TYPE_DEFAULT_ISOLATION:         'default',

    TIMEOUT_2_MINS: 120000,

    CREATE_VOLUMES_MAXIMUM: 32,

    MTU_MINI:   1280,
    MTU_MAX:    9216,
    MTU_DEFAULT: 1500,
    MTU_JUMBO:   9000,
    
    REPLICATION_THROTTLING_LIMIT_4GB: 4294967296,
    REPLICATION_THROTTLING_LIMIT_16KB: 16384,
    REPLICATION_THROTTLING_LIMIT_128KB: 131072,
    REPLICATION_THROTTLING_LIMIT_256KB: 262144,

    FC_INITIATOR_ALL: 'FC_ALL',
    iSCSI_INITIATOR_ALL: 'iSCSI_ALL',

    FED_AUTH_LDAP:                  'ldap',

    DISKPROPHET_DEVTYPE_UNKNOWN:    'unknown',
    DISKPROPHET_DEVTYPE_HDD:        'HDD',
    DISKPROPHET_DEVTYPE_SSD:        'SSD',
    DISKPROPHET_DEVTYPE_SSDNVME:    'SSD NVME',
    DISKPROPHET_DEVTYPE_SSDSAS:     'SSD SAS',
    DISKPROPHET_DEVTYPE_SSDSATA:    'SSD SATA',
    DISKPROPHET_DEVTYPE_HDDSAS:     'HDD SAS',
    DISKPROPHET_DEVTYPE_HDDSATA:    'HDD SATA',

    ENCLOSURE_DISK_NOT_INSTALLED:   '#bebebe',
    ENCLOSURE_DISK_NORMAL:          '#a2b983',
    ENCLOSURE_DISK_LESS_10:         '#FCE4D6',
    ENCLOSURE_DISK_BT_10_30:        '#FFF2CC',
    ENCLOSURE_DISK_BT_30_45:        '#E2EFDA',
    ENCLOSURE_DISK_UNKNOWN:         '#7D7D7D',
    ENCLOSURE_DISK_LESS_10_B:       '#F8CBAD',
    ENCLOSURE_DISK_BT_10_30_B:      '#FFE699',
    ENCLOSURE_DISK_BT_30_45_B:      '#C6E0B4',
    ENCLOSURE_DISK_NORMAL_C:        '#70AE47',
    ENCLOSURE_DISK_LESS_10_C:       '#CA7D49',
    ENCLOSURE_DISK_BT_10_30_C:      '#CAAE49',

    DISKPROPHET_PHASE_V1: 10,
    DISKPROPHET_PHASE_V2: 30,
    DISKPROPHET_PHASE_V3: 45,

    DISKPROPHET_PHASE_V2_V1: 14,
    DISKPROPHET_PHASE_V2_V2: 45,

    DISKPROPHET_PHASE_V2_S1: 'Bad',//'< 14 Days',
    DISKPROPHET_PHASE_V2_S2: 'Warning',//'< 45 Days',
    DISKPROPHET_PHASE_V2_S3: 'Good',//'> 45 Days',
    DISKPROPHET_PHASE_V2_UNKNOWN: 'Unknown',
    DISKPROPHET_PHASE_V2_NOT_READY: 'Not_Ready',

    DISKPROPHET_DEVTYPE_H:          'H',
    DISKPROPHET_DEVTYPE_S:          'S',
    DISKPROPHET_DEVTYPE_N:          'N',

    DISKPROPHET_DEFAULT_HOST_CLOUD: 'api.aiservice.io',

    DISKPROPHET_EDITION_CLOUD:      'Cloud',
    DISKPROPHET_EDITION_ON_PREMISES:    'On-Premises',

    DISKPROPHET_LAST_RESULT_OK:     'Ok',

    SEARCH_TOOL_COMBO_ID_PREFIX: 'search-tool-combo-',
    TRANSACTION_ABORTED: 'transaction aborted',
    COMMUNICATION_FAILURE: 'communication failure'
});
